version: "3.6"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    ports:
      - "8422:80"
      - "8445:8445"
    volumes:
      - ./src:/usr/share/nginx/sites
    restart: always
