version: "3.6"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    ports:
      - "8322:80"
    volumes:
      - ./src:/usr/share/nginx/sites
    restart: always
