version: "3.6"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    ports:
      - "127.0.0.1:8422:80"
      - "127.0.0.1:8445:8445"
    volumes:
      - ./src:/usr/share/nginx/sites
    restart: always
